pointerqueue:
	@ g++ pointerQtest.cpp -o pointerQ
	@ ./pointerQ
	@ rm -rf pointerQ
	
mergelists:
	@ g++ mergelists.cpp -o mergelists
	@ ./mergelists
	@ rm -rf mergelists

listconcat:
	@ g++ listconcat.cpp -o listconcat
	@ ./listconcat
	@ rm -rf listconcat

loctree:
	@ g++ locTreeTest.cpp -o loctree
	@ ./loctree
	@ rm -rf loctree

lcrtree:
	@ g++ lcrTreeTest.cpp -o lcrtree
	@ ./lcrtree
	@ rm -rf lcrtree	

postorder:
	@ g++ postorder.cpp -o postorder
	@ ./postorder
	@ rm -rf postorder

preorder:
	@ g++ preorder.cpp -o preorder
	@ ./preorder
	@ rm -rf preorder

timing:
	@ g++ timing.cpp -o timing
	@ ./timing
	@ rm -rf timing

levelorder:
	@ g++ levelorder.cpp -o levelorder
	@ ./levelorder
	@ rm -rf levelorder