time:
	@ g++ timing.cpp -o timer
	@ ./timer
	@ rm -rf timer
	
arraylist:
	@ g++ ArrayList.cpp -o ArrayListTest
	@ ./ArrayListTest
	@ rm -rf ArrayListTest

arraystack:
	@ g++ ArrayStack.cpp -o ArrayStackTest
	@ ./ArrayStackTest
	@ rm -rf ArrayStackTest

pointerlist:
	@ g++ PointerList.cpp -o PointerListTest
	@ ./PointerListTest
	@ rm -rf PointerListTest

pointerstack:
	@ g++ PointerStack.cpp -o PointerStackTest
	@ ./PointerStackTest
	@ rm -rf PointerStackTest