adjmatrix:
	@ python3 adjmatrix.py

floyd:
	@ python floyd.py

dfs:
	@ python dfs.py

trie:
	@ python trie.py

fftdyadic:
	@ python3 fftdyadic.py

fftany:
	@ python3 fftany.py

openhash:
	@ g++ openhash.cpp -o openhash
	@ ./openhash
	@ rm -rf openhash

closedhash:
	@ g++ closedhash.cpp -o closedhash
	@ ./closedhash
	@ rm -rf closedhash